### ISSUE TITLE
Que tipo de licencia Creative commons vamos a usar para el material multimedia? 

### ISSUE THREAD

**Issue by abr4xas** [ngVenezuela/press-kit#1]
Saludos,

La pregunta es esa, cual licencia vamos a usar?

Yo sugiero que usemos esta:

Atribución-NoComercial-SinDerivadas 
**CC BY-NC-ND**
<img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-nd/4.0/88x31.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">Licencia Creative Commons Atribución-NoComercial-SinDerivar 4.0 Internacional.</a>

> Esta licencia es la más restrictiva de nuestras seis licencias principales, permitiendo a otros solo descargar tu obra y compartirla con otros siempre y cuando te den crédito, pero no permiten cambiarlas de forma alguna ni usarlas comercialmente.

[Resumen de la licencia](https://creativecommons.org/licenses/by-nc-nd/4.0/).

Ya que el _manifesto_ indica:

> Ningún miembro de esta comunidad está en la potestad de solicitar remuneración económica por impartir conocimientos y/o instruir sobre "Javascript" o "Angular" utilizando el nombre de "ngVenezuela" cómo organización.

Por lo cual creo conveniente que no debemos permitir que alguien use nuestro material y le saque provecho económicamente.

**Comment by Villanuevand** [comment]
Me parece que está licencia es la ideal. 
Para proyectos propios utilizaremos GPL V3.0.

**Comment by abr4xas** [comment]
Y por que no la GPLv2?

**Comment by Villanuevand** [comment]
Buena pregunta @abr4xas.

Podemos hacer una investigación sobre ambas licencias y elegir la más apegada a nuestro manifesto y propósitos cómo comunidad.

**Comment by andoniabedul** [comment]
Discrepo en que se use esta licencia... El conocimiento debe ser libre, y que la gente apoye basandose en nuestros códigos; siempre y cuando digan que se obtuvo de ngVenezuela

Apoyo esta: 
![](http://es.creativecommons.org/blog/wp-content/uploads/2013/04/by-nc-sa.eu_petit.png)
Reconocimiento – NoComercial – CompartirIgual (by-nc-sa): No se permite un uso comercial de la obra original ni de las posibles obras derivadas, la distribución de las cuales se debe hacer con una licencia igual a la que regula la obra original.

**Comment by abr4xas** [comment]
Ya va, estamos hablando para la parte multimedia o el código que podamos generar a medida que estemos trabajando?

Si es para el contenido multimedia tienes razón.

**Comment by Villanuevand** [comment]
Cual licencias nos propones @akh000.
Vamos a discutir alguna para dar por cerrado esta incidencia.

**Comment by abr4xas** [comment]
### Licencia para el código que genere la comunidad **ngVenezuela**

GPLv2 vs GPLv3

> Cuando decimos que GPLv2 y GPLv3 son incompatibles, esto significa que no hay una manera legal de combinar código bajo GPLv2 con código bajo GPLv3 en un sólo programa. Esto es porque ambas GPLv2 y GPLv3 son licencias copyleft: ambas dicen "Si tú incluyes código bajo esta licencia en un programa más grande, ese programa más grande debe estar licenciado bajo esta licencia también". No hay modo de hacerlas compatibles. Podríamos agregar una cláusula de compatibilidad a la GPLv3, pero eso no cumpliría bien el trabajo, porque GPLv2 necesitaría una cláusula similar.

Fuente http://www.mastermagazine.info/articulo/11778.php

Entonces:

Si revisamos el [repo](https://github.com/angular/angular.js/blob/master/LICENSE) de Angular vemos que usan MIT el texto diferencia tres puntos::
- Condiciones, la condición es que la nota de copyright y la parte de los derechos se incluya en todas las copias o partes sustanciales del Software. Esta es la condición que invalidaría la licencia en caso de no cumplirse.
- Derechos, los derechos son muchos: sin restricciones; incluyendo usar, copiar, modificar, integrar con otro Software, publicar, sublicenciar o vender copias del Software, y además permitir a las personas a las que se les entregue el Software hacer lo mismo.
- Limitación de responsabilidad, finalmente se tiene un disclaimer o nota de limitación de la responsabilidad habitual en este tipo de licencias.

### Características y usos de esta licencia

Esta licencia permite reutilizar el software así licenciado tanto para ser software libre como para ser software no libre, permitiendo no liberar los cambios realizados al programa original.

También permite licenciar dichos cambios con licencia BSD, GPL u otra cualquiera que sea compatible (es decir, que cumpla las cláusulas de distribución).

Con esta licencia se tiene software libre. Ejemplos en los que podría interesar su aplicación serían las licencias duales, si se pretende difundir un estándar mediante una implementación de referencia, o si simplemente se pretende que el producto sea Libre sin mayores consideraciones.

Fuente: https://es.wikipedia.org/wiki/Licencia_MIT

### Podemos decir que:

La comunidad **ngVenezuela** puede licenciar el código bajo MIT sin problema alguno.

### Sobre el contenido multimedia:

Aun mantengo que debería ser CC BY-NC-ND

**Comment by andoniabedul** [comment]
Hablaba del contenido multimedia @abr4xas 
y con respecto a la licencia a usar en el código, la que comentaste me parece bien.

**Comment by abr4xas** [comment]
Entonces:
- Para el material grafico Licencia Creative Commons Atribución-NoComercial-SinDerivar 4.0 Internacional.
- Para el codigo que podamos generar usamos MIT

**Comment by alexsalas** [comment]
Artistic License 2.0
Copyright (c) 2015 ngVenezuela

**Comment by Villanuevand** [comment]
Estoy de acuerdo con @alexsalas. Para los que no conozcan esta licencia se basa principalmente en estos: 

> Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

**Comment by Villanuevand** [comment]
Fue mi error, cerra la incidencia. Queda abierta hasta que den su opinión.

**Comment by ajsb85** [comment]
:+1: 
CC BY-NC-ND

**Comment by abr4xas** [comment]
Creo que nos quedamos con esta licencia.
