### ISSUE TITLE
Actualizar el logo de comunidad

### ISSUE THREAD

**Issue by dianjuar** [ngVenezuela/press-kit#5]
La comunidad tiene nuevo logo, ya se ha actualizado en redes sociales y en mayoría de plataformas.

Actualizar el nuevo logo para que toda la comunidad pueda usarlo

FYI @Skatox

**Comment by Skatox** [comment]
Gracias por avisar, se han actualizado los logos en b0e462c425f83846adede035835c21e3f8bbb44e
